# Generated by Django 2.0.7 on 2018-07-13 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherBankUserInfo',
            fields=[
                ('guest_user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('guest_fullname', models.CharField(max_length=256)),
                ('other_bank_account_no', models.CharField(db_index=True, max_length=13, unique=True)),
                ('other_bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_accounts.OtherBanks')),
            ],
        ),
        migrations.CreateModel(
            name='UserBeneficiaries',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('beneficiary_id', models.BigIntegerField()),
                ('nickname', models.CharField(max_length=10)),
                ('beneficiary_account_no', models.CharField(db_index=True, max_length=13, unique=True)),
                ('beneficiary_fullname', models.CharField(max_length=256)),
                ('is_guest', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=256, unique=True)),
                ('password', models.CharField(max_length=256, unique=True)),
                ('fullname', models.CharField(max_length=256)),
                ('user_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='userbeneficiaries',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_users.Users'),
        ),
    ]
