# Generated by Django 2.0.7 on 2018-07-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=256),
        ),
    ]
