# Generated by Django 2.0.7 on 2018-07-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_users', '0003_auto_20180713_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
