# Generated by Django 2.0.7 on 2018-07-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_users', '0005_auto_20180714_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbeneficiaries',
            name='beneficiary_account_no',
            field=models.CharField(db_index=True, max_length=13),
        ),
    ]
