# Generated by Django 2.0.7 on 2018-07-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('depositor_account_no', models.CharField(max_length=13)),
                ('recipient_account_no', models.CharField(max_length=13)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionsFailed',
            fields=[
                ('transaction_histid', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.BigIntegerField()),
                ('depositor_account_no', models.CharField(max_length=13)),
                ('recipient_account_no', models.CharField(max_length=13)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionsSucceeded',
            fields=[
                ('transaction_histid', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.BigIntegerField()),
                ('depositor_account_no', models.CharField(max_length=13)),
                ('recipient_account_no', models.CharField(max_length=13)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
